name: Documentation

permissions:
  contents: read

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pdoc pytest

      - name: Install humemai package
        run: |
          python -m pip install .

      - name: Create output directory
        run: |
          rm -rf _docs 
          mkdir _docs

      - name: Build documentation
        run: |
          python -m pdoc -d google -o _docs humemai

      - name: Verify docs directory exists
        run: ls -lah _docs  # Debugging step

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4  # UPDATED TO LATEST VERSION
        with:
          name: documentation  # Ensure this name is used in download step
          path: "./_docs/"
          retention-days: 1  # Optional: keep artifact for only 1 day

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download documentation artifact
        uses: actions/download-artifact@v4  # UPDATED TO LATEST VERSION
        with:
          name: documentation  # Make sure this matches the upload step
          path: "./_docs/"

      - name: Verify downloaded artifact
        run: ls -lah _docs  # Debugging step

      - id: deployment
        uses: actions/deploy-pages@v2
